name : Deploy en VPS

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest

        #Define entorno, y clona el repo del VPS volatil
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            
            - name: Install sshpass
              run: sudo apt-get install sshpass -y
            

